version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-custom-expense-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expensesystem
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306" # Optional: map port to host